name: Terraform Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - stage
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Terraform Plugin Cache Directory Exists
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Set ENV and Run Terraform
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "Detected base branch: $BASE_BRANCH"
          cd /home/github/actions-runner/_work/walkthrough/walkthrough

          case "$BASE_BRANCH" in
            dev)
              ./run dev network init -var-file=../dev.tfvars
              ./run dev network plan -var-file=../dev.tfvars -out=../tfplan
              ;;
            stage)
              ./run stage network init -var-file=../stage.tfvars
              ./run stage network plan -var-file=../stage.tfvars -out=../tfplan
              ;;
            main)
              ./run pro network init -var-file=../pro.tfvars
              ./run pro network plan -var-file=../pro.tfvars -out=../tfplan
              ;;
            *)
              echo "Unsupported base branch: $BASE_BRANCH"
              exit 1
              ;;
          esac
