name: Terraform Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - stage
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x

      - name: Cache Terraform Directory
        uses: actions/cache@v4
        with:
          path: |
            walkthrough/walkthrough/.terraform
            walkthrough/walkthrough/.terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('walkthrough/walkthrough/**/*.tf') }}
          restore-keys: terraform-${{ runner.os }}-

      - name: Set Github Branch & Terraform Infra
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          INFRA_STATE=network

          echo "Detected base branch: $BASE_BRANCH"

          case "$BASE_BRANCH" in
            dev)
              echo "INFRA_ENV=dev" >> $GITHUB_ENV
              echo "VAR_FILE=../dev.tfvars" >> $GITHUB_ENV
              echo "ENV_OUT_FILE=../dev-tfplan" >> $GITHUB_ENV
              ;;
            stage)
              echo "INFRA_ENV=stage" >> $GITHUB_ENV
              echo "VAR_FILE=../stage.tfvars" >> $GITHUB_ENV
              echo "ENV_OUT_FILE=../stage-tfplan" >> $GITHUB_ENV
              ;;
            main)
              echo "INFRA_ENV=prod" >> $GITHUB_ENV
              echo "VAR_FILE=../prod.tfvars" >> $GITHUB_ENV
              echo "ENV_OUT_FILE=../prod-tfplan" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported base branch: $BASE_BRANCH"
              exit 1
              ;;
          esac

          # Also export these
          echo "INFRA_STATE=$INFRA_STATE" >> $GITHUB_ENV

      - name: Initialize Terraform Config
        working-directory: walkthrough/walkthrough
        run: |
          echo "Initializing..."
          ./run "$INFRA_ENV" "$INFRA_STATE" init -var-file="$VAR_FILE" -upgrade=false

      - name: Plan Terraform Infra
        run: |
          echo "Planning..."
          ./run "$INFRA_ENV" "$INFRA_STATE" plan -var-file="$VAR_FILE" -out="$ENV_OUT_FILE"

      # - name: Apply Terraform Infra
      #   run: |
      #     echo "Setting up infra..."

      #     ./run "$INFRA_ENV" "$INFRA_STATE" apply "$ENV_OUT_FILE"

      # - name: Terraform Destroy & Apply
      #   run: |
      #     echo "Getting ready.."
      #     ./run "$INFRA_ENV" "$INFRA_STATE" plan -destroy -out="$ENV_OUT_FILE"
      #     ./run "$INFRA_ENV" "$INFRA_STATE" apply "$ENV_OUT_FILE"
