name: Terraform Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - stage
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Terraform Plugin Directory
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-plugin-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-plugin-${{ runner.os }}-

      - name: Cache Terraform Working Directory
        uses: actions/cache@v3
        with:
          path: ./walkthrough/.terraform
          key: terraform-dir-${{ runner.os }}-${{ hashFiles('walkthrough/**/*.tf') }}
          restore-keys: |
            terraform-dir-${{ runner.os }}-

      - name: Debug Base Branch
        run: |
          echo "Base branch: $BASE_BRANCH"
          echo "Event full JSON:"
          echo "${{ toJson(github.event) }}"
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}

      - name: Set ENV based on Base Branch
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"

          case "$BASE_BRANCH" in
            dev)
              echo "ENV=dev" >> $GITHUB_ENV
              ;;
            stage)
              echo "ENV=stage" >> $GITHUB_ENV
              ;;
            main)
              echo "ENV=prod" >> $GITHUB_ENV
              ;;
            *)
              echo "Unsupported base branch: $BASE_BRANCH"
              exit 1
              ;;
          esac

      - name: Run Terraform Init & Plan Based on ENV

        run: |
          case "${ENV}" in
            dev)
              echo "Running Terraform for development..."
              cd walkthrough/walkthrough
              ./run dev network init -var-file=../../dev.tfvars
              ./run dev network plan -var-file=../../dev.tfvars -out=../../tfplan
              ;;
            stage)
              echo "Running Terraform for staging..."
              cd walkthrough/walkthrough
              ./run stage network init -var-file=../../stage.tfvars
              ./run stage network plan -var-file=../../stage.tfvars -out=../../tfplan
              ;;
            prod)
              echo "Running Terraform for production..."
              cd walkthrough/walkthrough
              ./run pro network init -var-file=../../pro.tfvars
              ./run pro network plan -var-file=../../pro.tfvars -out=../../tfplan
              ;;
            *)
              echo "Unknown environment: ${ENV}"
              exit 1
              ;;
          esac
